language: php

sudo: false

env:
  - NETTE=default
  - NETTE=~2.3.0
  - NETTE=~2.3.0 PREFER_LOWEST=true
  - NETTE=~2.4.0
  - NETTE=~2.4.0 PREFER_LOWEST=true

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  exclude:
    - php: 5.5
      env: NETTE=~2.4.0
    - php: 5.5
      env: NETTE=~2.4.0 PREFER_LOWEST=true
    - php: 5.5
      env: NETTE=default

before_install:
  - composer self-update
  - php .travis.composer.php

install:
  - composer install --no-interaction --prefer-source --ignore-platform-reqs
  - if  [ $PREFER_LOWEST = 'true' ]; then composer update --prefer-lowest --prefer-stable --ignore-platform-reqs; fi

script:
  - vendor/bin/parallel-lint -e php,phpt src tests
  - vendor/bin/phpcs -sp --standard=vendor/nella/coding-standard/Nella/ruleset.xml src tests
  - vendor/bin/tester -s -p php -c tests/php.ini tests --coverage build/coverage.xml --coverage-src src

  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose --config build/coveralls.yml || true

